//
// Generated file, do not edit! Created by opp_msgtool 6.0 from transaction.msg.
//

#ifndef __TRANSACTION_M_H
#define __TRANSACTION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Transaction;
/**
 * Class generated from <tt>transaction.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Transaction
 * {
 *     int ID;
 *     simtime_t startTransaction;
 * }
 * </pre>
 */
class Transaction : public ::omnetpp::cMessage
{
  protected:
    int ID = 0;
    omnetpp::simtime_t startTransaction = SIMTIME_ZERO;

  private:
    void copy(const Transaction& other);

  protected:
    bool operator==(const Transaction&) = delete;

  public:
    Transaction(const char *name=nullptr, short kind=0);
    Transaction(const Transaction& other);
    virtual ~Transaction();
    Transaction& operator=(const Transaction& other);
    virtual Transaction *dup() const override {return new Transaction(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getID() const;
    virtual void setID(int ID);

    virtual omnetpp::simtime_t getStartTransaction() const;
    virtual void setStartTransaction(omnetpp::simtime_t startTransaction);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Transaction& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Transaction& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Transaction *fromAnyPtr(any_ptr ptr) { return check_and_cast<Transaction*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TRANSACTION_M_H

